//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mix2dsp.rc
//
#define IDD_INPUT_FORM                  101
#define IDR_MAINFRAME                   128
#define IDD_GRAPHDLG                    130
#define IDD_DELTAK                      137
#define IDD_ENERGY                      138
#define IDD_LENSOPT                     140
#define IDR_PLOT_CTRL                   154
#define IDB_BITMAP1                     156
#define IDD_PLOTPROP                    158
#define IDD_PLOTPROPSHT1                159
#define IDD_PLOTPROPSHT2                161
#define IDC_WAVELENGTH_S                1000
#define IDC_WAVELENGTH_I                1001
#define IDC_WAVELENGTH_P                1002
#define IDC_INDEX_S                     1003
#define IDC_INDEX_I                     1004
#define IDC_INDEX_P                     1005
#define IDC_GVI_S                       1006
#define IDC_GVI_I                       1007
#define IDC_GVI_P                       1008
#define IDC_GVD_S                       1009
#define IDC_GVD_I                       1010
#define IDC_GVD_P                       1011
#define IDC_PHASE_S                     1012
#define IDC_PHASE_I                     1013
#define IDC_PHASE_P                     1014
#define IDC_RIN_S                       1015
#define IDC_RIN_I                       1016
#define IDC_RIN_P                       1017
#define IDC_ROUT_S                      1018
#define IDC_ROUT_I                      1019
#define IDC_ROUT_P                      1020
#define IDC_ALPHA_S                     1021
#define IDC_ALPHA_I                     1022
#define IDC_ALPHA_P                     1023
#define IDC_ENERGY_S                    1024
#define IDC_ENERGY_I                    1025
#define IDC_ENERGY_P                    1026
#define IDC_DURATION_S                  1027
#define IDC_DURATION_I                  1028
#define IDC_DURATION_P                  1029
#define IDC_DELAY_S                     1030
#define IDC_DELAY_I                     1031
#define IDC_BEAMDIAM_S                  1033
#define IDC_BEAMDIAM_I                  1034
#define IDC_BEAMDIAM_P                  1035
#define IDC_WALKOFF_S                   1036
#define IDC_WALKOFF_I                   1037
#define IDC_WALKOFF_P                   1038
#define IDC_RADCURV_S                   1039
#define IDC_RADCURV_I                   1040
#define IDC_RADCURV_P                   1041
#define IDC_XPOINTS                     1042
#define IDC_YPOINTS                     1043
#define IDC_TPOINTS                     1044
#define IDC_XGRID                       1045
#define IDC_YGRID                       1046
#define IDC_STATIC_X                    1050
#define IDC_CRYSTLENGTH                 1051
#define IDC_DEFF                        1052
#define IDC_DELTAK                      1053
#define IDC_ZSTEP                       1054
#define IDC_DIST                        1055
#define IDC_STATIC_Y                    1056
#define IDC_STATIC_T                    1057
#define IDC_STATIC_SIGNAL               1058
#define IDC_STATIC_IDLER                1059
#define IDC_STATIC_PUMP                 1060
#define IDC_ACCEPT                      1062
#define IDC_TYPE_SIG                    1063
#define IDC_TYPE_IDL                    1064
#define IDC_TYPE_PUM                    1065
#define IDC_RUNBTN                      1066
#define IDC_FLUENCE                     1067
#define IDC_GRAPH_HELP                  1068
#define IDC_HELPBOX                     1069
#define IDC_FARFIELD                    1069
#define IDC_MOVIE                       1070
#define IDC_LOADPLOT                    1071
#define IDC_NORMPOWER                   1072
#define IDC_STATIC_ROT                  1073
#define IDC_UPROT                       1074
#define IDC_DOWNROT                     1075
#define IDC_LEFTROT                     1076
#define IDC_RIGHTROT                    1077
#define IDC_RESETROT                    1078
#define IDC_POWER                       1079
#define IDC_SPECTRA                     1080
#define IDC_PRINTBTN                    1081
#define IDC_BEAM_FT                     1082
#define IDC_BEAM_FT2                    1083
#define IDC_RUNERG                      1083
#define IDC_M_W                         1084
#define IDC_RUNLENS                     1084
#define IDC_ANALYZE                     1085
#define IDC_FOCUS_W                     1086
#define IDC_M_P                         1087
#define IDC_TILT                        1088
#define IDC_FOCUS_P                     1089
#define IDC_PROGRESS_SLICE              1090
#define IDC_PROGRESS_TOTAL              1091
#define IDC_PROGRESS_SCAN               1092
#define IDC_EDITPLOT                    1093
#define IDC_DKINIT                      1095
#define IDC_DKFINAL                     1096
#define IDC_NDK                         1097
#define IDC_ERGIDL_INIT                 1098
#define IDC_ERGIDL_FINAL                1099
#define IDC_ERGLBL_P                    1100
#define IDC_ERGPUMP_INIT                1101
#define IDC_ERGPUMP_FINAL               1102
#define IDC_ERGLBL_I                    1103
#define IDC_ERGLBL_S                    1104
#define IDC_ERGSIG_INIT                 1105
#define IDC_ERGSIG_FINAL                1106
#define IDC_NERG                        1107
#define IDC_LENSPICT                    1108
#define IDC_FOCUS                       1109
#define IDC_BEAMSIZE                    1110
#define IDC_DISTANCE                    1111
#define IDC_LENSSCAN                    1112
#define IDC_DISTANCE_F                  1113
#define IDC_NDIST                       1114
#define IDC_STATIC_BEAMDIAM             1115
#define IDC_STATIC0                     1116
#define IDC_STATIC_FOCUS                1117
#define IDC_STATIC_DIST_I               1118
#define IDC_STATIC_DIST_F               1119
#define IDC_STATIC_NDIST                1120
#define IDC_STATIC_CAP                  1121
#define IDC_PLOTFRM                     1132
#define IDC_PLOTTABS                    1134
#define IDC_FRAME                       1136
#define IDC_LABEL                       1137
#define IDC_STATIC1                     1137
#define IDC_GRID                        1138
#define IDC_STATIC2                     1138
#define IDC_RADIO_MODEL0                1139
#define IDC_RADIO_MODEL1                1140
#define IDC_RADIO_MODEL2                1141
#define IDC_MODELTYPE                   1142
#define IDC_N2_S1                       1149
#define IDC_N2_S2                       1150
#define IDC_N2_S3                       1151
#define IDC_N2_I1                       1152
#define IDC_N2_I2                       1153
#define IDC_N2_I3                       1154
#define IDC_N2_P1                       1155
#define IDC_N2_P2                       1156
#define IDC_N2_P3                       1157
#define IDC_GAUSS_S                     1160
#define IDC_GAUSS_I                     1161
#define IDC_GAUSS_P                     1162
#define IDC_BETA_S1                     1163
#define IDC_BETA_S2                     1164
#define IDC_BETA_S3                     1165
#define IDC_BETA_I1                     1166
#define IDC_BETA_I2                     1167
#define IDC_BETA_I3                     1168
#define IDC_BETA_P1                     1169
#define IDC_BETA_P2                     1170
#define IDC_BETA_P3                     1181
#define IDC_RUNDK                       1200
#define IDC_OFFSET_S                    1210
#define IDC_OFFSET_I                    1211
#define ID_EXTRAS_KVEC                  32772
#define ID_EXTRAS_ERG                   32773
#define ID_EXTRAS_LENS                  32774
#define ID_FITALL                       32776
#define ID_ZOOMIN                       32777
#define ID_ZOOMOUT                      32778
#define ID_ZOOMVERT                     32779
#define ID_BUTTON32780                  32780
#define ID_BUTTON32781                  32781
#define ID_ZOOMHOR                      32781
#define ID_BUTTON32782                  32782
#define ID_ROTATE                       32783
#define ID_PAN                          32784
#define ID_EDITPLOT                     32785
#define ID_EDIT2                        32786
#define ID_SOLID                        32787
#define ID_WIRE                         32788
#define ID_DOTS                         32789
#define ID_BUTTON32790                  32790
#define ID_FRAME                        32790
#define ID_BUTTON32791                  32791
#define ID_BUTTON32792                  32792
#define ID_SELECTBOX                    32793
#define ID_SCALERGN                     32794
#define ID_BUTTON32795                  32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1143
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
